#!/usr/bin/env python3
"""Install repo-local language hooks into OpenCode plugin directories."""

from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PLUGINS_DIR = ROOT / "plugins"
GENERATED_HEADER = "// Generated by codex-lang-hooks install_opencode_plugin.py"


@dataclass(frozen=True)
class InstallTarget:
    plugin_name: str
    source_module: Path
    proxy_path: Path


def split_plugin_names(value: str) -> list[str]:
    names = [name.strip() for name in value.split(",") if name.strip()]
    if not names:
        raise ValueError("--plugins must be 'all' or at least one plugin name.")
    return names


def discover_opencode_plugins() -> list[str]:
    if not PLUGINS_DIR.exists():
        return []
    return sorted(
        path.parent.parent.name
        for path in PLUGINS_DIR.glob("*/opencode/plugin.mjs")
        if path.is_file()
    )


def selected_plugins(value: str) -> list[str]:
    if value == "all":
        plugins = discover_opencode_plugins()
        if not plugins:
            raise ValueError("No OpenCode plugins found under plugins/*/opencode.")
        return plugins

    plugins = split_plugin_names(value)
    missing = [
        name
        for name in plugins
        if not (PLUGINS_DIR / name / "opencode" / "plugin.mjs").is_file()
    ]
    if missing:
        raise ValueError(
            "Unknown OpenCode plugin(s): "
            + ", ".join(missing)
            + ". Expected plugins with opencode/plugin.mjs.",
        )
    return plugins


def opencode_plugin_dir(scope: str, project_dir: str | None) -> Path:
    if scope == "global":
        return Path.home() / ".config" / "opencode" / "plugins"

    if project_dir is None:
        raise ValueError("--project-dir is required when --scope project.")
    return Path(project_dir).expanduser().resolve() / ".opencode" / "plugins"


def proxy_content(plugin_name: str, source_module: Path) -> str:
    source_url = source_module.resolve().as_uri()
    return (
        f"{GENERATED_HEADER}\n"
        f"// Plugin: {plugin_name}\n"
        f"export {{ default }} from {source_url!r};\n"
        f"export * from {source_url!r};\n"
    )


def build_targets(plugin_names: list[str], output_dir: Path) -> list[InstallTarget]:
    return [
        InstallTarget(
            plugin_name=name,
            source_module=PLUGINS_DIR / name / "opencode" / "plugin.mjs",
            proxy_path=output_dir / f"{name}.mjs",
        )
        for name in plugin_names
    ]


def can_overwrite(path: Path, *, force: bool) -> bool:
    if not path.exists():
        return True
    if force:
        return True
    try:
        return path.read_text().startswith(GENERATED_HEADER)
    except UnicodeDecodeError:
        return False


def install_targets(
    targets: list[InstallTarget],
    *,
    dry_run: bool,
    force: bool,
) -> None:
    for target in targets:
        if not can_overwrite(target.proxy_path, force=force):
            raise ValueError(
                f"Refusing to overwrite non-generated file: {target.proxy_path}. "
                "Pass --force to replace it.",
            )

    for target in targets:
        sys.stdout.write(
            f"{'Would install' if dry_run else 'Installing'} "
            f"{target.plugin_name} -> {target.proxy_path}\n",
        )
        if dry_run:
            continue
        target.proxy_path.parent.mkdir(parents=True, exist_ok=True)
        target.proxy_path.write_text(
            proxy_content(target.plugin_name, target.source_module),
        )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--scope",
        choices=("global", "project"),
        required=True,
        help="Install into the global or project OpenCode plugin directory.",
    )
    parser.add_argument(
        "--project-dir",
        help="Project root for --scope project.",
    )
    parser.add_argument(
        "--plugins",
        default="all",
        help="Comma-separated plugin names, or 'all' for every OpenCode plugin.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print planned proxy files without writing them.",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing non-generated proxy files.",
    )
    args = parser.parse_args()

    try:
        plugins = selected_plugins(args.plugins)
        output_dir = opencode_plugin_dir(args.scope, args.project_dir)
        install_targets(
            build_targets(plugins, output_dir),
            dry_run=args.dry_run,
            force=args.force,
        )
    except ValueError as error:
        raise SystemExit(str(error)) from error


if __name__ == "__main__":
    main()
